// Copyright 2025 TiKV Project Authors. Licensed under Apache-2.0.

use std::sync::Arc;

use bytes::Bytes;
use dashmap::DashSet;

use crate::dfs::{Dfs, Error, FileType, Options, Result, S3Fs};

/// An DFS with an "overlay".
///
/// New writes will be put to `overlay` FS.
/// Read will firstly send to the `overlay` fs then `base` fs.
///
/// This can be used to isolate new write files and existing files.
/// Useful when performing light-weight forking write opreations like packing
/// backup.
pub struct OverlaidFs {
    base: Arc<S3Fs>,
    overlay: Arc<S3Fs>,
    overlay_written: DashSet<(FileType, u64)>,
}

impl OverlaidFs {
    /// Create a new OverlaidFs with the given base and overlay S3Fs.
    pub fn new(base: Arc<S3Fs>, overlay: Arc<S3Fs>) -> Self {
        Self {
            base,
            overlay,
            overlay_written: Default::default(),
        }
    }

    /// Get the base S3Fs.
    pub fn base_fs(&self) -> &Arc<S3Fs> {
        &self.base
    }

    /// Get the overlay S3Fs.
    pub fn overlay_fs(&self) -> &Arc<S3Fs> {
        &self.overlay
    }

    /// Check if a file is modified in the overlay layer by the `OverlaidFs`.
    ///
    /// Notice: This only check newly written files and if a file was already
    /// existing when creating this `OverlaidFs`, it won't be counted as a
    /// "modified" file.
    pub fn file_is_modified(&self, file_type: FileType, file_id: u64) -> bool {
        self.overlay_written.contains(&(file_type, file_id))
    }

    /// Get a list of modified files in the overlay layer by the `OverlaidFs`.
    ///
    /// Notice: This only check newly written files and if a file was already
    /// existing when creating this `OverlaidFs`, it won't be counted as a
    /// "modified" file.

    pub fn modified_files(&self) -> Vec<(FileType, u64)> {
        self.overlay_written.iter().map(|v| *v).collect()
    }
}

#[async_trait::async_trait]
impl Dfs for OverlaidFs {
    /// exists checks if the file exists in the DFS.
    async fn exists(&self, file_id: u64, opts: Options) -> Result<bool> {
        // Check in the write layer first, then the base layer.
        let res = self.overlay.exists(file_id, opts).await;
        match res {
            Ok(false) | Err(Error::NoSuchKey(..) | Error::NotExists(..)) => {
                self.base.exists(file_id, opts).await
            }
            any_other => any_other,
        }
    }

    /// read_file reads the whole file to memory.
    /// It can be used by remote compaction server that doesn't have local disk.
    async fn read_file(&self, file_id: u64, opts: Options) -> Result<Bytes> {
        // Try to read from the write layer first, then the base layer.
        let res = self.overlay.read_file(file_id, opts).await;
        match res {
            Err(Error::NoSuchKey(..) | Error::NotExists(..)) => {
                self.base.read_file(file_id, opts).await
            }
            any_other => any_other,
        }
    }

    /// Create creates a new File.
    /// The shard_id and shard_ver can be used determine where to write the
    /// file.
    async fn create(&self, file_id: u64, data: Bytes, opts: Options) -> Result<()> {
        self.overlay.create(file_id, data.clone(), opts).await?;
        self.overlay_written.insert((opts.file_type, file_id));
        Ok(())
    }

    /// remove removes the file from the DFS.
    /// `file_len` is used to choose proper storage class for cost
    /// efficiency, in bytes.
    /// `None` if file_len is unknown when invoke this method.
    async fn remove(&self, _file_id: u64, _file_len: Option<u64>, _opts: Options) {
        panic!("Call `remove` in OverlayS3Fs isn't allowed.");
    }

    /// Remove the file from DFS permanently.
    async fn permanently_remove(&self, _file_id: u64, _opts: Options) -> Result<()> {
        panic!("Call `permanently_remove` in OverlayS3Fs isn't allowed.");
    }

    /// get_runtime gets the tokio runtime for the DFS.
    fn get_runtime(&self) -> &tokio::runtime::Runtime {
        self.base.get_runtime()
    }
}

// Test cases are generated by Copilot, with Claude 4 Sonnet.
#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use bytes::Bytes;

    use super::*;
    use crate::dfs::{test_util::new_test_s3fs, FileType, Options};

    #[test]
    fn test_overlay_fs_read_file() {
        ::test_util::init_log_for_test();

        let base_data = "base_layer_data".to_string().into_bytes();
        let write_data = "write_layer_data".to_string().into_bytes();
        // Create mock instances that return the appropriate data
        let base_s3fs = Arc::new(new_test_s3fs(&base_data));
        let write_s3fs = Arc::new(new_test_s3fs(&write_data));
        let overlay_fs = OverlaidFs::new(base_s3fs.clone(), write_s3fs.clone());

        let file_id1 = 456u64;
        let file_id2 = 457u64;
        let opts = Options::default();
        let runtime = overlay_fs.get_runtime();

        // Test reading non-existent file
        let result = runtime.block_on(overlay_fs.read_file(file_id1, opts));
        result.unwrap_err();

        // Create file only in base layer
        runtime
            .block_on(base_s3fs.create(file_id1, Bytes::from(base_data.clone()), opts))
            .unwrap();

        // Should read from base layer (mock returns the base_data)
        let result = runtime.block_on(overlay_fs.read_file(file_id1, opts));
        assert_eq!(result.unwrap(), Bytes::from(base_data));

        // Create file in write layer
        runtime
            .block_on(overlay_fs.create(file_id2, Bytes::from(write_data.clone()), opts))
            .unwrap();

        // Should read from write layer (mock returns the write_data)
        let result = runtime.block_on(overlay_fs.read_file(file_id2, opts));
        assert_eq!(result.unwrap(), Bytes::from(write_data));
    }

    #[test]
    fn test_overlay_fs_create() {
        ::test_util::init_log_for_test();

        let file_data = "overlay_create_test".to_string().into_bytes();
        let base_s3fs = Arc::new(new_test_s3fs(&file_data));
        let write_s3fs = Arc::new(new_test_s3fs(&file_data));
        let overlay_fs = OverlaidFs::new(base_s3fs.clone(), write_s3fs.clone());

        let file_id = 789u64;
        let opts = Options::default();
        let runtime = overlay_fs.get_runtime();

        assert!(!overlay_fs.file_is_modified(FileType::Sst, file_id));
        // Create file through overlay
        let create_data = Bytes::from(file_data.clone());
        runtime
            .block_on(overlay_fs.create(file_id, create_data.clone(), opts))
            .unwrap();

        // File should exist in write layer
        let write_exists = runtime.block_on(write_s3fs.exists(file_id, opts));
        assert!(write_exists.unwrap());

        // File should not exist in base layer
        let base_exists = runtime.block_on(base_s3fs.exists(file_id, opts));
        assert!(!base_exists.unwrap());

        // Reading through overlay should work (returns mock data)
        let read_result = runtime
            .block_on(overlay_fs.read_file(file_id, opts))
            .unwrap();
        assert_eq!(read_result, create_data);
        assert!(overlay_fs.file_is_modified(FileType::Sst, file_id));
    }

    #[test]
    #[should_panic(expected = "Call `remove` in OverlayS3Fs isn't allowed.")]
    fn test_overlay_fs_remove_panics() {
        let file_data = "panic_test_data".to_string().into_bytes();
        let base_s3fs = Arc::new(new_test_s3fs(&file_data));
        let write_s3fs = Arc::new(new_test_s3fs(&file_data));
        let overlay_fs = OverlaidFs::new(base_s3fs, write_s3fs);

        let file_id = 999u64;
        let opts = Options::default();
        let runtime = overlay_fs.get_runtime();

        // This should panic
        runtime.block_on(overlay_fs.remove(file_id, None, opts));
    }
}
