// Copyright 2022 TiKV Project Authors. Licensed under Apache-2.0.

use tikv_util::config::{AbsoluteOrPercentSize, ReadableDuration, ReadableSize};

#[derive(Clone, Serialize, Deserialize, PartialEq, Debug)]
#[serde(default)]
#[serde(rename_all = "kebab-case")]
pub struct Config {
    /// Compress a log batch if its size exceeds this value. Setting it to zero
    /// disables compression.
    ///
    /// Default: "8KB"
    pub batch_compression_threshold: ReadableSize,
    /// Target file size for rotating log files.
    ///
    /// Default: "512MB"
    pub target_file_size: ReadableSize,

    /// Limit the worker io
    ///
    /// Default: "125MB"
    pub worker_rate_limit: ReadableSize,

    /// The directory to store the wal files for synchronous write.
    /// It's used to reduce the latency of writing wal.
    pub wal_sync_dir: String,

    /// The directory to support double write for low tail latency.
    pub wal_secondary_dir: String,

    /// One of the double writer becomes unhealthy when its fall behind size
    /// exceeds this value.
    pub wal_double_write_unhealthy_size: ReadableSize,

    /// Whether to enable the lightweight backup.
    ///
    /// Default: false
    pub lightweight_backup: bool,

    /// Target file size for wal chunk files.
    ///
    /// Default: "64MB"
    pub wal_chunk_target_file_size: ReadableSize,

    /// Open RfEngine in cli mode used by tools. Skip serde for this field to
    /// avoid misconfiguration. If cli_mode is set, the sync WAL writer will
    /// avoid sync to improve performance.
    ///
    /// Default: false
    #[serde(skip)]
    pub cli_mode: bool,

    /// Open RfEngine without compaction. This is used for test and debug.
    ///
    /// Default: false
    #[serde(skip)]
    pub disable_compaction: bool,

    /// Rlog file cache capacity. Available only when `lightweight_backup` is
    /// enabled.
    ///
    /// Default: "128MB"
    pub rlog_cache_capacity: ReadableSize,

    /// Size of rlog files not more that this threshold will be cached in memory
    /// for performance.
    ///
    /// Default: "4KB"
    pub rlog_cache_size_threshold: ReadableSize,

    /// Memory limit of DFS worker.
    ///
    /// Default: "10%"
    pub dfs_worker_memory_limit: AbsoluteOrPercentSize,

    /// throttle duration per write when WAL compaction is lagging.
    pub write_throttle_duration: ReadableDuration,

    /// The number of threads to sync rlog files generated by compact WAL.
    pub compact_wal_sync_concurrency: usize,

    /// Size limit for the rlog data section in a single rlog file.
    ///
    /// During rlog generation, a new file is started once the data
    /// section exceeds this limit.
    ///
    /// Valid range: [16MB, 4GB]. Default: "256MB"
    pub rlog_file_size: ReadableSize,

    /// The number of bytes per second to compact WAL files.
    pub compact_bytes_per_sec: ReadableSize,

    /// Enable rate limiter for compact WAL files.
    pub enable_compact_rate_limiter: bool,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            batch_compression_threshold: ReadableSize::kb(8),
            target_file_size: ReadableSize::mb(512),
            worker_rate_limit: ReadableSize::mb(125),
            wal_sync_dir: "".to_owned(),
            wal_secondary_dir: "".to_owned(),
            wal_double_write_unhealthy_size: ReadableSize::mb(256),
            lightweight_backup: false,
            wal_chunk_target_file_size: ReadableSize::mb(64),
            cli_mode: false,
            disable_compaction: false,
            rlog_cache_capacity: ReadableSize::mb(128),
            rlog_cache_size_threshold: ReadableSize::kb(4),
            dfs_worker_memory_limit: AbsoluteOrPercentSize::Percent(10.0),
            write_throttle_duration: ReadableDuration::millis(10),
            compact_wal_sync_concurrency: 2,
            rlog_file_size: ReadableSize::mb(256),
            compact_bytes_per_sec: ReadableSize::mb(200),
            enable_compact_rate_limiter: false,
        }
    }
}

#[cfg(test)]
impl Config {
    pub(crate) fn new(target_file_size: usize) -> Self {
        let mut cfg = Self::default();
        cfg.target_file_size = ReadableSize(target_file_size as u64);
        cfg
    }
}
