// Copyright 2022 TiKV Project Authors. Licensed under Apache-2.0.

use std::path::Path;

use tikv_util::{
    config::{AbsoluteOrPercentSize, ReadableDuration, ReadableSize},
    warn,
};

use crate::{MAX_EPOCH_ROTATE_LEN, MIN_EPOCH_ROTATE_LEN};

#[derive(Clone, Serialize, Deserialize, PartialEq, Debug)]
#[serde(default)]
#[serde(rename_all = "kebab-case")]
pub struct Config {
    /// Compress a log batch if its size exceeds this value. Setting it to zero
    /// disables compression.
    ///
    /// Default: "8KB"
    pub batch_compression_threshold: ReadableSize,
    /// Target file size for rotating log files.
    ///
    /// Default: "512MB"
    pub target_file_size: ReadableSize,

    /// Limit the worker io
    ///
    /// Default: "125MB"
    pub worker_rate_limit: ReadableSize,

    /// The directory to store the wal files for synchronous write.
    /// It's used to reduce the latency of writing wal.
    pub wal_sync_dir: String,

    /// The directory to support double write for low tail latency.
    pub wal_secondary_dir: String,

    /// One of the double writer becomes unhealthy when its fall behind size
    /// exceeds this value.
    pub wal_double_write_unhealthy_size: ReadableSize,

    /// Whether to enable the lightweight backup.
    ///
    /// Default: false
    pub lightweight_backup: bool,

    /// Target file size for wal chunk files.
    ///
    /// Default: "64MB"
    pub wal_chunk_target_file_size: ReadableSize,

    /// Open RfEngine in cli mode used by tools. Skip serde for this field to
    /// avoid misconfiguration. If cli_mode is set, the sync WAL writer will
    /// avoid sync to improve performance.
    ///
    /// Default: false
    #[serde(skip)]
    pub cli_mode: bool,

    /// Open RfEngine without compaction. This is used for test and debug.
    ///
    /// Default: false
    #[serde(skip)]
    pub disable_compaction: bool,

    /// Rlog file cache capacity. Available only when `lightweight_backup` is
    /// enabled.
    ///
    /// Default: "128MB"
    pub rlog_cache_capacity: ReadableSize,

    /// Size of rlog files not more that this threshold will be cached in memory
    /// for performance.
    ///
    /// Default: "4KB"
    pub rlog_cache_size_threshold: ReadableSize,

    /// Memory limit of DFS worker.
    ///
    /// Default: "10%"
    pub dfs_worker_memory_limit: AbsoluteOrPercentSize,

    /// throttle duration per write when WAL compaction is lagging.
    pub write_throttle_duration: ReadableDuration,

    /// The number of threads to sync rlog files generated by compact WAL.
    pub compact_wal_sync_concurrency: usize,

    /// Size limit for the rlog data section in a single rlog file.
    ///
    /// During rlog generation, a new file is started once the data
    /// section exceeds this limit.
    ///
    /// Valid range: [16MB, 4GB]. Default: "256MB"
    pub rlog_file_size: ReadableSize,

    /// The number of bytes per second to compact WAL files.
    pub compact_bytes_per_sec: ReadableSize,

    /// Enable rate limiter for compact WAL files.
    pub enable_compact_rate_limiter: bool,

    /// WAL file will be rotated and overwritten on every `epoch_rotate_len`
    /// epoches.
    pub epoch_rotate_len: usize,

    /// Delay compaction with latest truncated index to reduce generated rlog
    /// file size.
    pub delay_compaction_epoches: usize,

    /// modified by test only, skip serde to avoid misconfiguration.
    #[serde(skip)]
    pub(crate) max_batch_size: ReadableSize,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            batch_compression_threshold: ReadableSize::kb(8),
            target_file_size: ReadableSize::mb(512),
            worker_rate_limit: ReadableSize::mb(125),
            wal_sync_dir: "".to_owned(),
            wal_secondary_dir: "".to_owned(),
            wal_double_write_unhealthy_size: ReadableSize::mb(256),
            lightweight_backup: false,
            wal_chunk_target_file_size: ReadableSize::mb(64),
            cli_mode: false,
            disable_compaction: false,
            rlog_cache_capacity: ReadableSize::mb(128),
            rlog_cache_size_threshold: ReadableSize::kb(4),
            dfs_worker_memory_limit: AbsoluteOrPercentSize::Percent(10.0),
            write_throttle_duration: ReadableDuration::millis(10),
            compact_wal_sync_concurrency: 2,
            rlog_file_size: ReadableSize::mb(256),
            compact_bytes_per_sec: ReadableSize::mb(200),
            enable_compact_rate_limiter: false,
            epoch_rotate_len: MIN_EPOCH_ROTATE_LEN,
            delay_compaction_epoches: 0,
            max_batch_size: ReadableSize::mb(256),
        }
    }
}

impl Config {
    pub fn validate(&mut self, dir: &str) -> Result<(), String> {
        // make sure epoch_rotate_len is valid.
        if self.epoch_rotate_len < MIN_EPOCH_ROTATE_LEN
            || self.epoch_rotate_len > MAX_EPOCH_ROTATE_LEN
        {
            return Err(format!(
                "rfengine epoch_rotate_len {} is invalid, it must be between {} and {}",
                self.epoch_rotate_len, MIN_EPOCH_ROTATE_LEN, MAX_EPOCH_ROTATE_LEN
            ));
        };
        // do not modify epoch_rotate_len if there are existing wal files.
        let wal_file_count = wal_file_count(Path::new(dir));
        if wal_file_count > 0 && wal_file_count != self.epoch_rotate_len {
            if wal_file_count < MIN_EPOCH_ROTATE_LEN {
                return Err(format!(
                    "rfengine wal_file_count {} is less than {}, maybe interrupted on initialization",
                    wal_file_count, MIN_EPOCH_ROTATE_LEN
                ));
            }
            // The existing wal files count is different from the configured
            // epoch_rotate_len, we keep the existing value.
            warn!(
                "rfengine epoch_rotate_len is modified from {} to {}, as there are existing wal files",
                self.epoch_rotate_len, wal_file_count
            );
            self.epoch_rotate_len = wal_file_count;
            if self.delay_compaction_epoches + MIN_EPOCH_ROTATE_LEN > self.epoch_rotate_len {
                // adjust delay_compaction_epoches as well.
                self.delay_compaction_epoches = self.epoch_rotate_len - MIN_EPOCH_ROTATE_LEN;
            }
        }
        if self.delay_compaction_epoches + MIN_EPOCH_ROTATE_LEN > self.epoch_rotate_len {
            return Err(format!(
                "invalid delay_compaction_epoches {} with epoch_rotate_len {}",
                self.delay_compaction_epoches, self.epoch_rotate_len
            ));
        }
        Ok(())
    }
}

pub(crate) fn wal_file_count(dir: &Path) -> usize {
    let mut count = 0;
    loop {
        let file_path = crate::engine::wal_file_path(dir, count);
        if !file_path.exists() {
            break;
        }
        count += 1;
    }
    count
}

#[cfg(test)]
impl Config {
    pub(crate) fn new(target_file_size: usize) -> Self {
        let mut cfg = Self::default();
        cfg.target_file_size = ReadableSize(target_file_size as u64);
        cfg
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn test_config_validate() {
        let tmp_dir = tempfile::Builder::new().tempdir().unwrap();
        let base_path = tmp_dir.path();

        // Test 1: Valid default configuration
        let mut cfg = Config::default();
        cfg.validate(base_path.to_str().unwrap()).unwrap();

        // Test 2: Invalid epoch_rotate_len - too low
        let mut cfg = Config::default();
        cfg.epoch_rotate_len = MIN_EPOCH_ROTATE_LEN - 1;
        assert!(cfg.validate(base_path.to_str().unwrap()).is_err());

        // Test 3: Invalid epoch_rotate_len - too high
        let mut cfg = Config::default();
        cfg.epoch_rotate_len = MAX_EPOCH_ROTATE_LEN + 1;
        assert!(cfg.validate(base_path.to_str().unwrap()).is_err());

        // Test 4: Existing WAL files - should adjust epoch_rotate_len
        let existing_files_path = base_path.join("existing_files");
        std::fs::create_dir(&existing_files_path).unwrap();
        create_wal_files(&existing_files_path, 6);

        let mut cfg = Config::default();
        cfg.epoch_rotate_len = 4; // Different from existing file count
        cfg.validate(existing_files_path.to_str().unwrap()).unwrap();
        assert_eq!(cfg.epoch_rotate_len, 6); // Should be adjusted to match existing files

        // Test interruption scenarios - WAL file count less than MIN_EPOCH_ROTATE_LEN
        test_interruption_scenario(base_path, "interruption_0_files", 0, true);
        test_interruption_scenario(base_path, "interruption_1_file", 1, false);
        test_interruption_scenario(base_path, "interruption_3_files", 3, false);
        test_interruption_scenario(base_path, "interruption_2_files", 2, false);
    }

    fn create_wal_files(dir: &Path, count: usize) {
        for i in 0..count {
            let wal_path = crate::engine::wal_file_path(dir, i);
            std::fs::write(&wal_path, b"test data").unwrap();
        }
    }

    fn test_interruption_scenario(
        base_path: &Path,
        subdir_name: &str,
        existing_files: usize,
        should_pass: bool,
    ) {
        let test_path = base_path.join(subdir_name);
        std::fs::create_dir(&test_path).unwrap();
        create_wal_files(&test_path, existing_files);

        let mut cfg = Config::default();
        let result = cfg.validate(test_path.to_str().unwrap());

        if should_pass {
            assert!(
                result.is_ok(),
                "Expected validation to pass for {} files",
                existing_files
            );
        } else {
            assert!(
                result.is_err(),
                "Expected validation to fail for {} files (less than MIN_EPOCH_ROTATE_LEN)",
                existing_files
            );
        }
    }
}
