[package]
name = "test_coprocessor"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
api_version = { workspace = true }
collections = { workspace = true }
concurrency_manager = { workspace = true }
engine_rocks = { workspace = true }
futures = "0.3"
kvproto = { workspace = true }
protobuf = "2"
resource_metering = { workspace = true }
security = { workspace = true }
test_storage = { workspace = true }
tidb_query_common = { workspace = true }
tidb_query_datatype = { workspace = true }
tikv = { workspace = true }
tikv_util = { workspace = true }
tipb = { workspace = true }
txn_types = { workspace = true }
