name: CD

on:
  push:
    branches:
      - cloud-engine
  workflow_dispatch:
    inputs:
      overwrite_gcr:
        description: "overwrite gcr daily-run image"
        type: boolean
        default: false

jobs:
  build-arm64:
    name: Build ARM64 Image
    runs-on: arm64
    timeout-minutes: 120
    steps:
      - name: Check out Code
        uses: actions/checkout@v2
      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          platforms: "linux/arm64"
          push: true
          network: "host"
          tags: |
            xexplorersun/tikv:cse-${{ github.sha }}-arm64
      - name: Build Image Harbor
        uses: docker/build-push-action@v2
        with:
          platforms: "linux/arm64"
          push: true
          network: "host"
          tags: |
            hub.pingcap.net/sunxiaoguang/serverless/tikv:${{ github.sha }}-arm64
  build-amd64:
    name: Build AMD64 Image
    runs-on: amd64
    timeout-minutes: 120
    outputs:
      image: tikv-cse:${{ github.sha }}-amd64
    steps:
      - name: Check out Code
        uses: actions/checkout@v2
      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          platforms: "linux/amd64"
          push: true
          network: "host"
          tags: |
            xexplorersun/tikv:cse-${{ github.sha }}-amd64
      - name: Build Image Harbor
        uses: docker/build-push-action@v2
        with:
          platforms: "linux/amd64"
          push: true
          network: "host"
          tags: |
            hub.pingcap.net/sunxiaoguang/serverless/tikv:${{ github.sha }}-amd64
  multi-arch:
    name: Create Multi-Architecture Image
    runs-on: amd64
    needs: ["build-arm64", "build-amd64"]
    steps:
      - name: create-manifest
        run: |
          docker manifest create xexplorersun/tikv:cse-${{ github.sha }} \
          --amend xexplorersun/tikv:cse-${{ github.sha }}-amd64 \
          --amend xexplorersun/tikv:cse-${{ github.sha }}-arm64
      - name: push-manifest
        run: |
          docker manifest push xexplorersun/tikv:cse-${{ github.sha }}
      - name: create-manifest-harbor
        run: |
          docker manifest create hub.pingcap.net/sunxiaoguang/serverless/tikv:${{ github.sha }} \
          --amend hub.pingcap.net/sunxiaoguang/serverless/tikv:${{ github.sha }}-amd64 \
          --amend hub.pingcap.net/sunxiaoguang/serverless/tikv:${{ github.sha }}-arm64
      - name: push-manifest-harbor
        run: |
          docker manifest push hub.pingcap.net/sunxiaoguang/serverless/tikv:${{ github.sha }}

  sync-image:
    name: Sync image to GCR
    runs-on: amd64
    needs: [ "multi-arch" ]
    if: ${{ inputs.overwrite_gcr || github.ref == 'refs/heads/cloud-engine' }}
    env:
      GCR_IMAGE: xexplorersun/tikv-cse:v6.6.0
      # Additional tag to label the image with the commit SHA.
      ADDITIONAL_TAG: xexplorersun/tikv-cse:cse-${{ github.sha }}
    steps:
      - name: Set runner architecture
        run: |
          arch=$(uname -m)
          if [ "$arch" = "x86_64" ]; then
            echo "ARCH=amd64" >> $GITHUB_ENV
          elif [ "$arch" = "aarch64" ]; then
            echo "ARCH=arm64" >> $GITHUB_ENV
          else
            echo "ARCH=$arch" >> $GITHUB_ENV
          fi
      - name: Install regctl
        run: |
          curl -sLO https://github.com/regclient/regclient/releases/download/v0.4.0/regctl-linux-${{ env.ARCH }}
          chmod +x regctl-linux-${{ env.ARCH }}
      - name: Sync Image
        run: |
          ./regctl-linux-${{ env.ARCH }} image copy xexplorersun/tikv:cse-${{ github.sha }} ${{ env.GCR_IMAGE }} -v info
          ./regctl-linux-${{ env.ARCH }} image copy xexplorersun/tikv:cse-${{ github.sha }} ${{ env.ADDITIONAL_TAG }} -v info
