name: CD

on:
  push:
    branches:
      - cloud-engine
  workflow_dispatch:
    inputs:
      overwrite_gcr:
        description: "overwrite gcr daily-run image"
        type: boolean
        default: false

jobs:
  build-arm64:
    name: Build ARM64 Image
    runs-on: arm64
    timeout-minutes: 120
    steps:
      - name: Check out Code
        uses: actions/checkout@v2

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          platforms: "linux/arm64"
          push: true
          tags: |
            xexplorersun/tikv:cse-${{ github.sha }}-arm64
  build-amd64:
    name: Build AMD64 Image
    runs-on: amd64
    timeout-minutes: 120
    outputs:
      image: tikv-cse:${{ github.sha }}-amd64
    steps:
      - name: Check out Code
        uses: actions/checkout@v2

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          platforms: "linux/amd64"
          push: true
          tags: |
            xexplorersun/tikv:cse-${{ github.sha }}-amd64
  multi-arch:
    name: Create Multi-Architecture Image
    runs-on: arm64
    needs: ["build-arm64", "build-amd64"]
    steps:
      - name: create-manifest
        run: |
          docker manifest create xexplorersun/tikv:cse-${{ github.sha }} \
          --amend xexplorersun/tikv:cse-${{ github.sha }}-amd64 \
          --amend xexplorersun/tikv:cse-${{ github.sha }}-arm64
      - name: push-manifest
        run: |
          docker manifest push xexplorersun/tikv:cse-${{ github.sha }}

  sync-image:
    name: Sync image to GCR
    runs-on: arm64
    needs: ["multi-arch"]
    if: ${{ inputs.overwrite_gcr || github.ref == 'refs/heads/cloud-engine' }}
    env:
      GCR_IMAGE: xexplorersun/tikv-cse:v6.6.0
    steps:
      - name: create-manifest
        run: |
          docker manifest create ${{ env.GCR_IMAGE }} \
          --amend xexplorersun/tikv:cse-${{ github.sha }}-amd64 \
          --amend xexplorersun/tikv:cse-${{ github.sha }}-arm64
      - name: push-manifest
        run: |
          docker manifest push ${{ env.GCR_IMAGE }}
