# Run a loop of random test to verify that it's functional
name: Random test

on:
  pull_request:
  workflow_dispatch:

# Concurrency ensures that only a single job or workflow using the same concurrency group will run at a time.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  dev:
    name: Run random tests
    runs-on: amd64
    env:
      RUSTFLAGS: -Dwarnings
      FAIL_POINT: "1"
      ROCKSDB_SYS_SSE: "1"
      RUST_BACKTRACE: "1"
      LOG_LEVEL: INFO
      EXTRA_CARGO_ARGS: --no-run
    steps:
      - uses: actions/checkout@v3
      - name: Check cmake & protoc # use local to work around github rate limit
        run: |
          cmake --version
          protoc --version
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.GIT_ACTION_BOT }}
        run: git config --global url."https://${TOKEN}@github.com/".insteadOf "https://github.com/"
      - name: Install `rust` toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Run random tests
        env:
          CARGO_INCREMENTAL: "0"
        working-directory: ./
        run: |
          cargo test -p tests --test random test_random_all > run.log 2>&1
      - name: Print log on error
        if: failure()
        run: tail -2500 run.log
